# Generated by Django 2.2.17 on 2021-01-17 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20210117_0029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopUserProfile',
            new_name='UserProfile',
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 9, 27, 53, 104409, tzinfo=utc)),
        ),
    ]
